# MULTI_RUN: true

DATALOADER:
  DATASET: "cityscapes"

SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 5000 # 10000
  GAMMA: 0.1
  EPOCHES: 200
  MAX_ITER: 90000
  MOMENTUM: 0.9
  STEPS:
  - 60000
  - 80000
  TEST_PERIOD: 0
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: constant
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0
  NESTEROV: false
  SCHEDULE_TYPE: "poly"
