# MULTI_RUN: true

DATALOADER:
  BATCH_SIZE_TEST: 4
  BATCH_SIZE_TRAIN: 2
  BATCH_SIZE_VAL: 4
  DATASET_PATH: /home/xianr/TurboRuns/cityscapes

SOLVER:
  BASE_LR: 0.01
  EPOCHES: 200
  SCHEDULE_TYPE: "poly"
  SHOW_IMAGE: true
